<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Keshalan art</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= asset('css/style.css'); ?>">
</head>
<body>
<header>

<div id="header-block">
    <div class="name-logo">

        <div class="logo gauche">
            <img src="<?= asset('images/logo-Keshalan.png'); ?>" alt="logo de Keshalan" id="logo-keshalan"> 

        </div>
        <div class="artist-name gauche">
            <h1> KESHALAN.<i>Art</i></h1>
            <p>L'Art comme  <br> moteur de <br> Vie</p>
        </div>
        

    </div> 
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<?php include $template . '.phtml'; ?>
</body>
</html>


